name = "a"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "a_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "a.wasm"
command = "npm run build:release"
